### ISSUE TITLE
May I ask if the author has studied the GAN network generation of three-dimensional images. like NII   image

### ISSUE THREAD

**Issue by Rudeguy1** [swelland6626/gan#3]

**Comment by swelland6626** [comment]
So the model input is  3D image in compressed nifti format and the output is a 2D image in compressed nifti format. The images are used in a downstream kidney segmentation task for which 3D spatial information from the input image is added back to the GAN output image.

**Comment by Rudeguy1** [comment]
Thanks for sharing
